In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
plt.rcParams['font.family'] = 'NanumGothic'

In [7]:
import os
# os.listdir('./code/5대질병/간질환/')
liverpath = './code/5대질병/간질환/'
liverfolders = os.listdir(liverpath)
liverfolders

['지방간.xlsx', '간의질환.xlsx', '간경변증.xlsx']

In [15]:
df_liver = pd.DataFrame()
df_livers = pd.DataFrame()
for liver in liverfolders:
    # print(type(liver))
    liverfind=os.path.join(liverpath,liver)
    # print(liverfind)
    df_liver = pd.read_excel(liverfind)
    df = df_liver.rename(columns = df_liver.iloc[2])
    df = df.drop(0,axis=0)
    df = df.drop(2,axis=0)
    df = df.drop('항목',axis=1)
    # print(df.info())

    # 여기서 선택권은 2가지 
    # float형으로 바꿔서 해당범위만 더하게 하기 or 글자들 따로 빼서 값들만 있는 표 만들어서 float형변환 후 더하고 따로 빼놓은 글자들 다시 합치기
    # .... 응 그냥 excel 써~
    df_gender = df.iloc[0]
    # df.astype(float) #-> object를 float형으로 바꾸기
    # df_livers = df_livers.iloc[3:3,23:62]+df.iloc[3:3,23:62]  
df_gender
# df_livers

/home/nhnacademy/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/home/nhnacademy/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/home/nhnacademy/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

성별구분              NaN
연령구분10세          진료년월
환자수         2022년 01월
내원일수              NaN
청구건수              NaN
              ...
환자수         2022년 12월
내원일수              NaN
청구건수              NaN
요양급여비용총액          NaN
보험자부담금            NaN
Name: 1, Length: 62, dtype: object

In [9]:
# df_liver.index[2]
# df_liver.drop(df_liver.index[0],axis=0,inplace=True)
# df_liver.drop(df_liver.iloc[0],axis=0,inplace=True)

# df_liver

In [10]:

# df = df_liver.drop(df_liver.index[1],axis=0)

df

,성별구분,연령구분10세,환자수,내원일수,청구건수,요양급여비용총액,보험자부담금,환자수,내원일수,청구건수,...,환자수,내원일수,청구건수,요양급여비용총액,보험자부담금,환자수,내원일수,청구건수,요양급여비용총액,보험자부담금
1,NaN,진료년월,2022년 01월,NaN,NaN,NaN,NaN,2022년 02월,NaN,NaN,...,2022년 11월,NaN,NaN,NaN,NaN,2022년 12월,NaN,NaN,NaN,NaN
3,계,계,30570.0,72897.0,44321.0,18698188.0,13642027.0,28349.0,63323.0,40367.0,...,32382.0,72246.0,47330.0,17631632.0,12651641.0,33424.0,68941.0,48235.0,15087749.0,10520853.0
4,남,소계,19275.0,46294.0,27849.0,12226792.0,8900273.0,17923.0,40091.0,25386.0,...,20057.0,45498.0,29124.0,11367031.0,8135103.0,20851.0,43775.0,29947.0,9879484.0,6871454.0
5,남,0_9세,4.0,7.0,5.0,2099.0,1738.0,2.0,5.0,5.0,...,3.0,3.0,3.0,444.0,343.0,3.0,7.0,5.0,2124.0,1908.0
6,남,10_19세,8.0,12.0,12.0,1085.0,841.0,12.0,23.0,16.0,...,8.0,9.0,9.0,2259.0,2017.0,11.0,15.0,15.0,717.0,409.0
7,남,20_29세,57.0,195.0,87.0,74390.0,55931.0,54.0,124.0,78.0,...,65.0,190.0,96.0,40269.0,28863.0,54.0,162.0,84.0,147059.0,124544.0
8,남,30_39세,473.0,1525.0,699.0,719384.0,566757.0,400.0,1062.0,576.0,...,410.0,1199.0,596.0,349831.0,254241.0,400.0,933.0,582.0,219503.0,152476.0
9,남,40_49세,2189.0,6205.0,3215.0,2231032.0,1705928.0,2034.0,5202.0,2884.0,...,2132.0,5568.0,3180.0,1835216.0,1368079.0,2221.0,5089.0,3206.0,1219104.0,852672.0
10,남,50_59세,5585.0,13556.0,8181.0,3822234.0,2798955.0,5029.0,11507.0,7143.0,...,5496.0,12811.0,8106.0,3510872.0,2532301.0,5631.0,12325.0,8245.0,3060651.0,2139763.0
11,남,60_69세,6751.0,15545.0,9685.0,3620673.0,2572880.0,6373.0,13328.0,9027.0,...,7273.0,15605.0,10433.0,3745249.0,2654871.0,7655.0,15228.0,10873.0,3549745.0,2488338.0
12,남,70_79세,3383.0,6937.0,4758.0,1268064.0,850539.0,3218.0,6907.0,4480.0,...,3675.0,7658.0,5280.0,1442030.0,983834.0,3872.0,7577.0,5495.0,1274284.0,833626.0
13,남,80세이상,842.0,2312.0,1207.0,487832.0,346704.0,815.0,1933.0,1177.0,...,1010.0,2455.0,1421.0,440862.0,310554.0,1015.0,2439.0,1442.0,406297.0,277719.0
14,여,소계,11295.0,26603.0,16472.0,6471396.0,4741753.0,10426.0,23232.0,14981.0,...,12325.0,26748.0,18206.0,6264601.0,4516538.0,12573.0,25166.0,18288.0,5208265.0,3649399.0
15,여,0_9세,4.0,14.0,6.0,1326.0,1155.0,3.0,20.0,4.0,...,4.0,4.0,4.0,238.0,214.0,4.0,5.0,5.0,467.0,426.0
16,여,10_19세,8.0,24.0,16.0,5520.0,4599.0,9.0,11.0,11.0,...,8.0,13.0,13.0,1008.0,574.0,8.0,11.0,11.0,857.0,566.0
17,여,20_29세,42.0,130.0,62.0,32166.0,24259.0,45.0,123.0,69.0,...,55.0,180.0,87.0,168741.0,128938.0,51.0,131.0,72.0,45232.0,36714.0
18,여,30_39세,305.0,1065.0,445.0,391215.0,307491.0,273.0,821.0,400.0,...,321.0,1149.0,535.0,449255.0,352194.0,299.0,763.0,454.0,256411.0,200463.0
19,여,40_49세,1103.0,3022.0,1654.0,1061872.0,828220.0,1014.0,2499.0,1467.0,...,1185.0,3067.0,1785.0,917365.0,685449.0,1159.0,3090.0,1755.0,1075164.0,830179.0
20,여,50_59세,2451.0,5349.0,3545.0,1467754.0,1080735.0,2261.0,4619.0,3231.0,...,2545.0,5024.0,3765.0,1242431.0,911752.0,2534.0,4671.0,3721.0,923458.0,625623.0
21,여,60_69세,3616.0,7286.0,5279.0,1775663.0,1288670.0,3267.0,6525.0,4727.0,...,3939.0,7531.0,5814.0,1701971.0,1210738.0,4155.0,7243.0,6024.0,1377038.0,927563.0
22,여,70_79세,2617.0,5918.0,3772.0,1113573.0,766141.0,2453.0,5151.0,3491.0,...,2905.0,5858.0,4202.0,1073564.0,720089.0,3002.0,5585.0,4288.0,947115.0,625070.0
23,여,80세이상,1163.0,3795.0,1693.0,622307.0,440483.0,1112.0,3463.0,1581.0,...,1378.0,3922.0,2001.0,710027.0,506589.0,1370.0,3667.0,1958.0,582522.0,402795.0